version: '3.7'

services:
  client-react-nginx:
    image: nelsonct7/machine-front-end:latest
    init: true
    networks:
      - frontend
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  api-appointment:
    image: nelsonct7/machine-back-end:latest
    init: true
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://root:password@db:27017/
    networks:
      - frontend
      - backend
    ports:
      - target: 3002
        published: 3002
        protocol: tcp
        mode: host
    deploy:
      replicas: 1

  db:
    image: mongo
    networks:
      - backend
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    deploy:
      replicas: 1
    
volumes:
  dbdata:
    driver: local

networks:
  frontend:
  backend: